// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestReverse_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewReverse()

	called := false
	cmd.CommandAction = func(c *Reverse) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--word-mode")
	args = append(args, "--json")
	args = append(args, "--dry-run")
	args = append(args, "--interactive")
	args = append(args, "--recursive")
	args = append(args, "--include")
	args = append(args, "test")
	args = append(args, "--exclude")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.wordMode != true {
		t.Errorf("Expected wordMode to be true, got '%v'", cmd.wordMode)
	}
	if cmd.outputJSON != true {
		t.Errorf("Expected outputJSON to be true, got '%v'", cmd.outputJSON)
	}
	if cmd.dryRun != true {
		t.Errorf("Expected dryRun to be true, got '%v'", cmd.dryRun)
	}
	if cmd.interactive != true {
		t.Errorf("Expected interactive to be true, got '%v'", cmd.interactive)
	}
	if cmd.recursive != true {
		t.Errorf("Expected recursive to be true, got '%v'", cmd.recursive)
	}
}

func TestReverse_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewReverse()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
