// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSkillInstall_Execute(t *testing.T) {

	parent := &Skill{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSkillInstall()

	called := false
	cmd.CommandAction = func(c *SkillInstall) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--scope")
	args = append(args, "test")
	args = append(args, "--agent")
	args = append(args, "test")
	args = append(args, "--replace")
	args = append(args, "--ref")
	args = append(args, "test")
	args = append(args, "--path")
	args = append(args, "test")
	args = append(args, "--name")
	args = append(args, "test")
	args = append(args, "test")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.scope != "test" {
		t.Errorf("Expected scope to be 'test', got '%v'", cmd.scope)
	}
	if cmd.agent != "test" {
		t.Errorf("Expected agent to be 'test', got '%v'", cmd.agent)
	}
	if cmd.replace != true {
		t.Errorf("Expected replace to be true, got '%v'", cmd.replace)
	}
	if cmd.ref != "test" {
		t.Errorf("Expected ref to be 'test', got '%v'", cmd.ref)
	}
	if cmd.path != "test" {
		t.Errorf("Expected path to be 'test', got '%v'", cmd.path)
	}
	if cmd.name != "test" {
		t.Errorf("Expected name to be 'test', got '%v'", cmd.name)
	}
	if cmd.source != "test" {
		t.Errorf("Expected source to be 'test', got '%v'", cmd.source)
	}
	if cmd.nameOrPath != "test" {
		t.Errorf("Expected nameOrPath to be 'test', got '%v'", cmd.nameOrPath)
	}
}

func TestSkillInstall_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &Skill{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSkillInstall()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
