// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestSkillInspect_Execute(t *testing.T) {

	parent := &Skill{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSkillInspect()

	called := false
	cmd.CommandAction = func(c *SkillInspect) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--scope")
	args = append(args, "test")
	args = append(args, "--agent")
	args = append(args, "test")
	args = append(args, "--json")
	args = append(args, "test")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.scope != "test" {
		t.Errorf("Expected scope to be 'test', got '%v'", cmd.scope)
	}
	if cmd.agent != "test" {
		t.Errorf("Expected agent to be 'test', got '%v'", cmd.agent)
	}
	if cmd.outputJSON != true {
		t.Errorf("Expected outputJSON to be true, got '%v'", cmd.outputJSON)
	}
	if cmd.name != "test" {
		t.Errorf("Expected name to be 'test', got '%v'", cmd.name)
	}
}

func TestSkillInspect_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &Skill{}
	parent.RootCmd = &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewSkillInspect()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
