// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"fmt"
	"os"
	"slices"
	"strconv"
	"strings"

	"errors"
	"github.com/arran4/rntocase/cmd"
	"github.com/arran4/rntocase/internal/cli"
)

var _ Cmd = (*Snake)(nil)

type Snake struct {
	*RootCmd
	Flags         *flag.FlagSet
	dryRun        bool
	interactive   bool
	files         []string
	SubCommands   map[string]func() Cmd
	CommandAction func(c *Snake) error
}

type UsageDataSnake struct {
	*Snake
	Recursive bool
}

func (c *Snake) Usage() {
	err := executeUsage(os.Stderr, "snake_usage.txt", UsageDataSnake{c, false})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Snake) UsageRecursive() {
	err := executeUsage(os.Stderr, "snake_usage.txt", UsageDataSnake{c, true})
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error generating usage: %s\n", err)
	}
}

func (c *Snake) Execute(args []string) error {
	var remainingArgs []string
	for i := 0; i < len(args); i++ {
		arg := args[i]
		if arg == "--" {
			remainingArgs = append(remainingArgs, args[i+1:]...)
			break
		}
		if strings.HasPrefix(arg, "--") {
			if arg == "--help" {
				c.Usage()
				return nil
			}
			name := arg[2:]
			value := ""
			hasValue := false
			if strings.Contains(name, "=") {
				parts := strings.SplitN(name, "=", 2)
				name = parts[0]
				value = parts[1]
				hasValue = true
			}
			_ = value
			_ = hasValue
			switch name {

			case "dryRun", "dry-run":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.dryRun = b
				} else {
					c.dryRun = true
				}

			case "interactive":
				if hasValue {
					b, err := strconv.ParseBool(value)
					if err != nil {
						return fmt.Errorf("invalid boolean value for flag %s: %s", name, value)
					}
					c.interactive = b
				} else {
					c.interactive = true
				}
			default:
				return fmt.Errorf("unknown flag: --%s", name)
			}
		} else if strings.HasPrefix(arg, "-") && arg != "-" {
			// Short flags
			shorts := arg[1:]
			for j := 0; j < len(shorts); j++ {
				char := string(shorts[j])
				if char == "h" {
					c.Usage()
					return nil
				}
				found := false

				if !found {
					return fmt.Errorf("unknown flag: -%s", char)
				}
			}
		} else {
			remainingArgs = append(remainingArgs, args[i:]...)
			break
		}
	}

	if len(remainingArgs) > 0 {
		if cmd, ok := c.SubCommands[remainingArgs[0]]; ok {
			return cmd().Execute(remainingArgs[1:])
		}
	}
	// Handle vararg files
	{
		varArgStart := 0
		if varArgStart > len(remainingArgs) {
			varArgStart = len(remainingArgs)
		}
		varArgs := remainingArgs[varArgStart:]
		c.files = varArgs
	}

	if c.CommandAction != nil {
		if err := c.CommandAction(c); err != nil {
			return fmt.Errorf("snake failed: %w", err)
		}
	} else {
		c.Usage()
	}

	return nil
}

func (c *RootCmd) NewSnake() *Snake {
	set := flag.NewFlagSet("snake", flag.ContinueOnError)
	v := &Snake{
		RootCmd:     c,
		Flags:       set,
		SubCommands: make(map[string]func() Cmd),
	}

	set.BoolVar(&v.dryRun, "dry-run", false, "Print the rename operations to be performed without executing them")

	set.BoolVar(&v.interactive, "interactive", false, "Prompt for confirmation before executing each rename operation")
	set.Usage = v.Usage

	v.CommandAction = func(c *Snake) error {

		err := cli.RunSnake(c.dryRun, c.interactive, c.files...)
		if err != nil {
			if errors.Is(err, cmd.ErrPrintHelp) {
				c.Usage()
				return nil
			}
			if errors.Is(err, cmd.ErrHelp) {
				fmt.Fprintf(os.Stderr, "Use '%s help' for more information.\n", os.Args[0])
				return nil
			}
			if e, ok := err.(*cmd.ErrExitCode); ok {
				return e
			}
			return fmt.Errorf("snake failed: %w", err)
		}
		return nil
	}

	v.SubCommands["help"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	v.SubCommands["usage"] = func() Cmd {
		return &InternalCommand{
			Exec: func(args []string) error {
				if slices.Contains(args, "-deep") {
					v.UsageRecursive()
					return nil
				}
				v.Usage()
				return nil
			},
			UsageFunc: v.Usage,
		}
	}
	return v
}
