// Code generated by github.com/arran4/go-subcommand/cmd/gosubc. DO NOT EDIT.

package main

import (
	"flag"
	"testing"
)

func TestTrim_Execute(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewTrim()

	called := false
	cmd.CommandAction = func(c *Trim) error {
		called = true
		return nil
	}

	args := []string{}
	args = append(args, "--algorithm")
	args = append(args, "test")
	args = append(args, "--trim-chars")
	args = append(args, "test")
	args = append(args, "--dry-run")
	args = append(args, "--interactive")

	err := cmd.Execute(args)
	if err != nil {
		t.Errorf("Unexpected error: %v", err)
	}

	if !called {
		t.Error("CommandAction was not called")
	}

	if cmd.algorithm != "test" {
		t.Errorf("Expected algorithm to be 'test', got '%v'", cmd.algorithm)
	}
	if cmd.trimChars != "test" {
		t.Errorf("Expected trimChars to be 'test', got '%v'", cmd.trimChars)
	}
	if cmd.dryRun != true {
		t.Errorf("Expected dryRun to be true, got '%v'", cmd.dryRun)
	}
	if cmd.interactive != true {
		t.Errorf("Expected interactive to be true, got '%v'", cmd.interactive)
	}
}

func TestTrim_ExecuteHelpAndUnknownFlags(t *testing.T) {

	parent := &RootCmd{
		FlagSet:  flag.NewFlagSet("root", flag.ContinueOnError),
		Commands: make(map[string]func() Cmd),
	}
	cmd := parent.NewTrim()

	if err := cmd.Execute([]string{"--help"}); err != nil {
		t.Errorf("--help returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"-h"}); err != nil {
		t.Errorf("-h returned an error: %v", err)
	}
	if err := cmd.Execute([]string{"--not-a-real-flag"}); err == nil {
		t.Error("expected an error for an unknown long flag")
	}
	if err := cmd.Execute([]string{"-?"}); err == nil {
		t.Error("expected an error for an unknown short flag")
	}
}
